# fly.toml app configuration file generated for harry-bot-discord on 2026-03-15T08:04:50-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'harry-bot-discord'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  MPLBACKEND = 'Agg'

[processes]
  app = 'python main.py'

[[vm]]
  memory = '2g'
  cpus = 1
  memory_mb = 2048
