# fly.toml app configuration file generated for harry-bot
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'harry-bot'
primary_region = 'sjc'

[build]
  dockerfile = "Dockerfile"

[env]
  # Matplotlib non-interactive backend
  MPLBACKEND = "Agg"

# We run this as a worker process, NOT a web service.
# DO NOT declare an [http_service] block, otherwise Fly will try to route web traffic to it
# and will restart the container when it fails health checks.
[processes]
  app = "python main.py"
